---
- hosts: all
  become: yes
  vars_files:
    - vars/provision_vars.yml

  roles:
    # Common server setup
    - common
    - configure-ssh
    - configure-ntpd

    # Additional configuration
    - configure-mariadb

    # Galaxy roles
    - geerlingguy.mysql