---
- hosts: webservers
  become: yes
  vars_files:
    - vars/provision_vars.yml

  roles:
    - geerlingguy.apache
    - geerlingguy.repo-epel
    - geerlingguy.repo-remi
    - geerlingguy.php
    - geerlingguy.composer
    - { role: geerlingguy.mailhog, when: install_mailhog }
    - configure-php
    - configure-httpd
    - { role: configure-mailhog, when: install_mailhog }