---
- hosts: all
  become: yes
  vars_files:
    - vars/provision_vars.yml

  roles:
    - geerlingguy.apache
    - geerlingguy.repo-epel
    - geerlingguy.repo-remi
    - geerlingguy.php
    - geerlingguy.composer
    - geerlingguy.mailhog
    - configure-php
    - configure-httpd
    - configure-mailhog