---
# Environment specific config

# Install Mailhog, useful for local development
install_mailhog: false

# If the deploy_user variable is set, attempt to set ownership of apache directories to this user
apache_vhost_permissions: false

# Turn this off for Vagrant, turn it on for anything else
apache_sendfile_option: "off"

# Incoming IP tables firewall rules
iptables_incoming_tcp_ports:
  - 22
  - 80
  - 443

# Extra rules
# iptables_extra_rules:
#   - "-A INPUT -p tcp -s 0.0.0.0 --dport 22 -m state --state NEW,ESTABLISHED -j ACCEPT"
#   - "-A OUTPUT -p tcp -s 0.0.0.0 --sport 22 -m state --state ESTABLISHED -j ACCEPT"

# Apache vhosts
apache_vhosts:
  - servername: "$SERVER_NAME$"
    documentroot: "$DOCUMENT_ROOT$"
    projectroot: "$PROJECT_PATH$"
    extra_parameters: |
      <FilesMatch "\.php$">
        Require all granted
        SetHandler proxy:fcgi://127.0.0.1:9000
      </FilesMatch>

# Apache SSL vhosts
apache_vhosts_ssl:
  - servername: "$SERVER_NAME$"
    documentroot: "$DOCUMENT_ROOT$"
    projectroot: "$PROJECT_PATH$"
    certificate_file: "/etc/pki/tls/certs/localhost.crt"
    certificate_key_file: "/etc/pki/tls/private/localhost.key"
    extra_parameters: |
      <FilesMatch "\.php$">
        Require all granted
        SetHandler proxy:fcgi://127.0.0.1:9000
      </FilesMatch>

# MySQL options
mysql_root_password: $MYSQL_ROOT_PASSWORD$
mysql_databases:
  - name: $MYSQL_DATABASE$
mysql_users:
  - name: $MYSQL_USER_NAME$
    host: "%"
    password: $MYSQL_USER_PASS$
    priv: "$MYSQL_USER_NAME$.*:ALL"

# mysql_root_password_update: yes