---
# Environment specific config

# geerlingguy.apache overrides
apache_vhosts:
  - servername: "$SERVER_NAME$"
    documentroot: "$DOCUMENT_ROOT$"
    projectroot: "$PROJECT_PATH$"
    extra_parameters: |
      <FilesMatch "\.php$">
        Require all granted
        SetHandler proxy:fcgi://127.0.0.1:9000
      </FilesMatch>

apache_vhosts_ssl:
  - servername: "$SERVER_NAME$"
    documentroot: "$DOCUMENT_ROOT$"
    projectroot: "$PROJECT_PATH$"
    certificate_file: "/etc/pki/tls/certs/localhost.crt"
    certificate_key_file: "/etc/pki/tls/private/localhost.key"
    extra_parameters: |
      <FilesMatch "\.php$">
        Require all granted
        SetHandler proxy:fcgi://127.0.0.1:9000
      </FilesMatch>

# geerlingguy.mysql overrides
mysql_root_password: $MYSQL_ROOT_PASSWORD$
mysql_databases:
  - name: $MYSQL_DATABASE$
mysql_users:
  - name: $MYSQL_USER_NAME$
    host: "%"
    password: $MYSQL_USER_PASS$
    priv: "$MYSQL_USER_NAME$.*:ALL"

# mysql_root_password_update: yes